#version: '3.8'
#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/test
#      SPRING_R2DBC_USERNAME: postgres
#      SPRING_R2DBC_PASSWORD: password
#    depends_on:
#      - db
#  db:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: test
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#    volumes:
#      - db-data:/var/lib/postgresql/data
#
#volumes:
#  db-data:
